### ISSUE TITLE
Tool Opens and Closes.

### ISSUE THREAD

**Issue by TheEpicKid** [M1NNEl/UnbanTool#1]
Tool just opens and closes. How do I get it to work?

**Comment by vossBDE** [comment]
idk but did you get any viruses? shit sus af

**Comment by M1NNEl** [comment]
fixed with new patch

**Comment by TheEpicKid** [comment]
No I haven’t gotten a virus but I haven’t tried to open the tool I’ll try
to redownload it and see if it works.
